let fontFamily = "'Overused Grotesk', Helvetica, Arial, sans-serif";

let titles = [
    "Novice",
    "Apprentice",
    "Trainee Swapper",
    "Graduate Swapper",
    "Experienced Swapper",
    "Senior Swapper",
    "Matcher",
    "Senior Matcher",
    "Elder Matcher",
    "Tiler",
    "Senior Tiler",
    "Elder Tiler",
    "Knight of Swaps",
    "Keeper of Tiles",
    "Match-Maker",
    "Match-Maker Master",
    "Power-Swapper",
    "Senior Power-Swapper",
    "Lightning Power-Swapper",
    "Master of Power-Swappers",
    "Swap Magician",
    "Swap Wizard",
    "Swap Sorcerer",
    "Match Master",
    "Royal Matcher",
    "Prince of Tiles",
    "King of Tiles",
    "All-Mighty Tiler",
    "Ruler of the Tile Planet",
    "Ruler of the Tile Star System",
    "Ruler of the Tile Galaxy",
    "Ruler of the Tile Supercluster",
    "The Chosen One",
    "The Worthy One",
    "Red Tile Demigod",
    "Green Tile Demigod",
    "Blue Tile Demigod",
    "Orange Tile Demigod",
    "Yellow Tile Demigod",
    "Purple Tile Demigod",
    "White Tile Demigod",
    "God of Matches Trainee",
    "Red God of Swaps",
    "Green God of Swaps",
    "Blue God of Swaps",
    "Orange God of Swaps",
    "Yellow God of Swaps",
    "Purple God of Swaps",
    "White God of Swaps",
    "High God of Swaps",
    "All-Seeing God of Swaps",
    "Eldery God of Swaps",
    "Tile Universe Keeper",
    "Tile Multiverse Keeper",
    "Tile Kiloverse Keeper",
    "Tile Megaverse Keeper",
    "Tile Gigaverse Keeper",
    "Tile Teraverse Keeper",
    "Tile Hyperverse Keeper",
    "Otherworldly Tile Keeper",
]